export const linksConfig = [
    //size is rem
    {
        title: 'דף הבית',
        path: '/home',
        component: 'HOMEPAGE',
        size: 2,
        padding: 2,
    },
    {
        title: 'מעוניין לקחת משכנתא חדשה',
        path: '/newMortgage',
        component: 'NEW_MORTGAGE',
        size: 2,
        padding: 2,
    },
    {
        title: 'רוצה לבדוק איפה הכי כדאי לי לקחת משכנתא',
        path: '/checkBestMortgage',
        component: 'CHECK_BEST_MORTGAGE',
        size: 1.5,
        padding: 4,
    },
    {
        title: 'מעוניין לקחת הלוואה רגילה',
        path: '/normalMortgage',
        component: 'NORMAL_MORTGAGE',
        size: 2,
        padding: 2,
    },
    {
        title: 'מעוניין לקחת הלוואה עד 100 אלף ש"ח',
        path: '/upTo100kLoan',
        component: 'UP_TO_100K_LOAN',
        size: 1.5,
        padding: 4,
    },
    {
        title: 'אני מעוניין לקחת הלוואה אחת',
        path: '/oneLoan',
        component: 'ONE_LOAN',
        size: 1.3,
        padding: 6,
        icon: 'info',
    },
    {
        title: 'אני מעוניין לקחת כמה הלוואת',
        path: '/fewLoans',
        component: 'FEW_LOANS',
        size: 1.3,
        padding: 6,
        icon: 'info',
    },
    {
        title: 'מעוניין לקחת הלוואה מעל 100 אלף ש"ח',
        path: '/over100kLoan',
        component: 'OVER100K_LOAN',
        size: 1.5,
        padding: 4,
    },
    {
        title: 'צור קשר',
        path: '/contactUs',
        component: 'CONTACT_US',
        size: 2,
        padding: 2,
    },
    {
        title: 'הרשמה',
        path: '/register',
        component: 'REGISTER',
        size: 2,
        padding: 2,
    },
    {
        title: 'שחזור חשבון',
        path: '/recover',
        component: 'Recover',
        size: 1,
        padding: 2,
    },
]