export const linksConfig = [
  {
    title: 'דף הבית',
    path: '/',
    component: 'HOMEPAGE',
    size: 2,
    padding: 2,
    },
  {
    title: 'מעוניין לקחת משכנתא חדשה',
    path: '/mortgages/new/checkBest',
    root:'/mortgages/new',
    component: 'NEW_MORTGAGE',
    size: 2,
    padding: 2,
  },
  {
    title: 'רוצה לבדוק איפה הכי כדאי לי לקחת משכנתא',
    path: '/mortgages/new/checkBest',
    root:'/mortgages/new/checkBest',
    component: 'CHECK_BEST_MORTGAGE',
    size: 1.5,
    padding: 4,
  },
  {
    title: 'מעוניין לקחת הלוואה רגילה',
    path: '/loans/normal/upTo100k/one',
    root:'/loans/normal',
    component: 'NORMAL_LOAN',
    size: 2,
    padding: 2,
  },
  {
    title: 'מעוניין לקחת הלוואה עד 100 אלף ש"ח',
    path: '/loans/normal/upTo100k/one',
    root:'/loans/normal/upTo100k',
    component: 'UP_TO_100K_LOAN',
    size: 1.5,
    padding: 4,
  },
  {
    title: 'אני מעוניין לקחת הלוואה אחת',
    path: '/loans/normal/upTo100k/one',
    root:'/loans/normal/upTo100k/one',
    component: 'ONE_LOAN',
    size: 1.3,
    padding: 6,
    icon: 'info',
  },
  {
    title: 'אני מעוניין לקחת כמה הלוואות',
    path: '/loans/normal/upTo100k/few',
    root:'/loans/normal/upTo100k/few',
    component: 'FEW_LOANS',
    size: 1.3,
    padding: 6,
    icon: 'info',
  },
  {
    title: 'מעוניין לקחת הלוואה מעל 100 אלף ש"ח',
    path: '/loans/normal/over100k',
    root:'/loans/normal/over100k',
    component: 'OVER100K_LOAN',
    size: 1.5,
    padding: 4,
  },
  {
    title: 'צור קשר',
    path: '/contact',
    root:'/contact',
    component: 'CONTACT_US',
    size: 2,
    padding: 2,
    },
  {
    title: 'שנה סיסמא',
    path: '/changePassword',
    root:'/changePassword',
    component: 'CHANGE_PASSWORD',
    size: 2,
    padding: 2,
  },
];
